export const sweetDishesList = [
  "Khoya",
  "Sandesh",
  "Boondi",
  "Mishti Doi",
  "Mohan Bhog",
  "Lobongo",
  "Nikruti",
  "Roshogulla",
  "Traditional Flan Custard",
  "Tres Leches Pastel",
  "Mexican Churros",
  "Mexican Chocolate Sauce",
  "Vietnamese Three Color Desserts",
  "Che Ba Mau or Chè Ba Mau Chè Ba Màu",
  "Che Bap or Chè Bắp – Sweet Corn Pudding",
  "Che Troi Nuoc or Chè Trôi Nước",
  "Che Chuoi or Chè Chuối",
  "Vietnamese Sweet Corn Pudding",
  "Vietnamese Sponge Cake",
  "Vietnamese Fruit Cocktail",
  "Tarta de Santiago",
  "Tarta de Queso",
  "Torrijas",
  "Crema Catalana",
  "Chocolate and Churros",
  "Turrón",
  "Mantecados",
  "Polvorones",
  "Flan",
  "Baklava",
  "Künefe",
  "Lokum",
  "Tavukgöğsü",
  "Kadayif and Kunefe",
  "Firinda Sutlac",
  "Tavuk Gogsu",
  "Asure",
  "Dessert",
  "Cupcake",
  "Chocolate Dessert",
  "Brownies",
  "Sweet Pastry",
  "Doughnut",
  "Frozen Dessert",
  "Milkshake",
  "Chocolate salami",
  "Napoleon cake",
  "Bird’s milk cake",
  "Russian Fudge",
  "Kartoshka",
  "Viktor Kuzmin",
  "Borshch",
  "Portuguese Custard Tarts",
  "Queijadas de Sintra",
  "Bola de Berlim",
  "Bolo Rei",
  "Pastéis de Nata",
  "Serradura Dessert",
  "Pao De Lo",
  "Chocolate Salami",
  "Ranginak",
  "Faloodeh",
  "Shirini Morabai",
  "Shirini Zaban",
  "Noon Khamei",
  "Qottab",
  "Persian Black Tea with Cardamom & Dried Rose Petals",
  "Kheer",
  "Gajjar Ka Halwa",
  "Gulab Jamun",
  "Sohan Halwa",
  "Halwa",
  "Barfi ",
  "Gulab Jamun",
  "Ras Malai",
  "Yomari",
  "Lakhamari",
  "Juju Dhau",
  "Jerry",
  "Gud-paak",
  "Til ko Laddu",
  "Peda",
  "Rasbari",
  "Khuwa Barfi",
  "Kheer",
  "Khajuri",
  "Italian Apple Olive Oil Cake",
  "Popped Quinoa Crunch Bar",
  "Honey Almond Ricotta Spread With Peaches",
  "Blueberry Muffins ",
  "Flourless Chocolate Olive Oil Cake",
  "Roasted Fruit",
  "Vegan Lemon Olive Oil Cake",
  "Maple Vanilla Baked Pears",
  "Pudding",
  "Layali lubnan",
  "Maamoul",
  "Shaabiyat",
  "Lebanese Baklava",
  "Halawet El Jibn",
  "Cookie",
  "Ma'amoul ",
  "Sweet Pastry",
  "Kunāfah",
  "Red bean porridge",
  "Sweet pancakes",
  "Sugar candy",
  "Shaved ice",
  "Bungeoppang",
  "Hotteok",
  "Sweet Pancake",
  "Sweet Rice Mini Bundt Cake",
  "Bingsu",
  "Shaved Ice",
  "Dalgona",
  "Sponge Candy",
  "Poached Pears",
  "Baesuk",
  "Sweet Korean Pancakes",
  "Blueberry Cream Cheese Babka",
  "Lekach",
  "Honey Cake",
  "Passover Rainbow Cookies",
  "Ingredient Chewy Coconut Macaroons",
  "Apricot Hamantaschen",
  "Mandel Bread",
  "Sufganiyah",
  "Easy Halva Recipe",
  "Rugelach",
  "Hanukkah Gelt",
  "Daifuku",
  "Green tea mochi",
  "matcha mochi",
  "Sakura mochi",
  "Japanese cherry blossom mochi",
  "Japanese parfait",
  "Japanese sweet potato dessert",
  "Mochi ice cream",
  "Japanese red bean paste",
  "anko",
  "Dango",
  "Black sesame seed cookies",
  "Traditional anmitsu",
  "Tiramisu",
  "Authentic Recipe",
  "Easy Classic Pizzelle Recipe",
  "Italian Waffle Cookies",
  "Chocolate Vanilla Berry Panna Cotta Tart",
  "Almond Biscotti Recipe with Cranberries",
  "Italian-Style Candied Chestnuts",
  "Italian Butter Cookies",
  "Canestrelli",
  "Italian Egg Yolk Cookies",
  "Traditional Italian Breakfast Cookies",
  "Easy Panettone Recipe",
  "Lemon Ricotta Cake with Almonds",
  "Guinness Chocolate Cake",
  "Irish Apple Cake",
  "Shamrock Shakes",
  "Irish Whiskey Truffles",
  "Irish Porter Cake",
  "Traditional Irish Barmbrack",
  "Irish Coffee",
  "Three Ingredient Potato Candy",
  "Irish Yellowman Candy",
  "Irish Shortbread",
  "Indian Carrot Pudding",
  "Indian Rice Pudding",
  "Indian Milk Balls",
  "Shrikhand",
  "Mango Halwa",
  "Toasted Coconut Ladoo",
  "Rasmalai",
  "Mysore Pak",
  "Boondi Ladoo",
  "Puran Poli",
  "Gerbeaud Cake",
  "Hungarian Chestnut Cake",
  "Hungarian Poppy Seed Bread Pudding",
  "Hungarian Chocolate Cake",
  "Hungarian Walnut Torte",
  "Hungarian Chocolate Biscuits",
  "Hungarian Baked Dessert Noodles",
  "Rakott Teszta",
  "Kakaós Csiga",
  "Hungarian Chocolate Rolls",
  "Butterhorn Cookies with Walnuts",
  "Chimney Cake",
  "Kürtőskalács",
  "Hawaiian Dream Cake",
  "Coconut Macadamia Nut Bars",
  "Hawaiian Cheesecake Bars",
  "Copycat Guri Guri",
  "Pineapple Upside Down Cake",
  "Haupia Cake",
  "Hawaiian Banana Nut Bread",
  "Chocolate Haupia Pie",
  "Ted’s Bakery Copycat",
  "Hawaiian POG Recipe",
  "Brown Sugar Grilled Pineapple",
  "Baklava",
  "Revani Cake",
  "Melopita",
  "Greek Honey Pie",
  "Milopita",
  "Greek Apple Spice Cake",
  "Yiaoutorpita Cake",
  "Loukomadies",
  "Greek donuts",
  "Melomakarona",
  "Greek honey cookies",
  "Kourabiethes",
  "Greek Christmas cookies",
  "Saint Fanourios Cake",
  "Greek Orange Semolina Cake",
  "German Plum Dumplings",
  "Zwetschgenknoedel",
  "Bee Sting Cake",
  "Blushing Maid",
  "Strawberry Rhubarb Trifle",
  "Sweet Venison Cake",
  "German Fruit Flan",
  "German Coconut Macaroons",
  "German Rum Balls",
  "German Cheesecake",
  "German Blueberry Cake",
  "Palmier Cookies",
  "Financiers",
  "Apple Cranberry Galette",
  "French Fig Tart",
  "Parisian Flan",
  "Ina Garten’s French Chocolate Bark",
  "Pears Belle Helene",
  "Crepes",
  "Cherry Clafoutis",
  "Madeleines",
  "Carrot and Sweet Potato Cake",
  "Fried Plantains with rum",
  "Creole Pancake",
  "Plantain Dosa",
  "Creole Banana and Lime Pie",
  "Pineapple upside down Cake",
  "Rice Pudding",
  "Soursop Crème Brulee",
  "Red Velvet Cake",
  "Red Been Bun",
  "Egg Tarts",
  "Tanghulu",
  "Pumpkin pancakes",
  "Fried Durian",
  "Tangyuan",
  "Sugarcoated Haws on a Stick",
  "Sweet Egg Bun",
  "Almond Jelly",
  "Soy Milk Pudding",
  "Old-Fashioned Cajun Cake",
  "Mardi Gras King Cake",
  "Beignets",
  "New Orleans Pralines",
  "Pumpkin Tarte à la Bouille",
  "Southern Sweet Potato Pie",
  "Louisiana Stranger Bundt Cake",
  "Cajun Sweet Dough Pies",
  "New Orleans-Style Bread Pudding",
  "Peach & Blackberry Cobbler",
  "Soft and Chewy Chocolate Chip Cookies",
  "Apple Pie",
  "Texas Sheet Cake",
  "Hershey’s Chocolate Cake",
  "Peanut Butter Brownies",
  "Juniors Cheese Cake",
  "Perfect Bananas Foster",
  "Jif Peanut Butter Cookies",
  "Old Fashioned Pecan Pie",
  "Nilla Wafer Banana Pudding",
  "Malva Pudding",
  "Chocolate Malva Pudding",
  "Moroccan Shortbread Cookies",
  "Melt-in-Mouth Butter Cookies",
  "Egyptian Ghorayebah",
  "West African Lime Cake",
  "Crunchies",
  "South African Oatmeal Bars",
  "Koeksisters",
  "Umm Ali",
  "Egyptian Bread Pudding",
  "South African Peppermint Crisp Fridge Tart",
  "Chebakia",
  "Moroccan Sesame Cookies",
];
